[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 5173
  port = 8888
  publish = "dist"
