[build]
  publish = "build"
  command = "CI=false npm run build"
  base = "/"

[build.environment]
  NODE_VERSION = "18"
  CI = "false"
  NPM_FLAGS = "--no-audit --no-fund"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 5173
  port = 8888
  publish = "dist"
